IsDebuggingActive: false

Commands:
  ClearChatRepeatBlankLine: 500

Colors:
  Detail: RED
  Error: DARK_RED
  ErrorDetail: RED
  Primary: GOLD
  Secondary: GRAY
  Success: GREEN
  Tertiary: DARK_GRAY
  Type: AQUA
  Username: YELLOW
  Value: YELLOW

Messages:
  JoinEvent: "&a&l+ &e%pd% &6has joined the server"
  QuitEvent: "&c&l- &e%pd% &6has left the server"