name: "TestPluginKT"
main: "io.github.tsgrissom.testpluginkt.TestPluginKT"
version: "1.0.0"
api-version: "1.20"

author: "tsgrissom"
description: "A lightweight Essentials replacer written in Kotlin"
website: "https://github.com/tsgrissom/TestPluginKT"

commands:
  # General (A-Z)
  gamemode:
    description: "Alter a player's gamemode"
    aliases: ["gm", "gma", "gmc", "gms", "gmsp"]
  heal:
    description: "Restores a player's health"
    aliases: ["eheal"]
  ping:
    description: "Check how long it takes to receive a response from the server"
    aliases: ["eping", "epong", "pong"]
  suicide:
    description: "Kills your player by force"
    aliases: ["esuicide", "seppuku", "selfdestruct"]
  whois:
    description: "Displays a bunch of player-related information"
    aliases: ["ewhoami", "ewhoami", "whoami"]
  # Time Setting (Earliest-Latest)
  day:
    description: "Sets a world's time to day"
  midnight:
    description: "Sets a world's time to midnight"
  night:
    description: "Sets a world's time to night"
  noon:
    description: "Sets a world's time to noon"
  sunset:
    description: "Sets a world's time to sunset"
    aliases: [ "dusk" ]
  sunrise:
    description: "Sets a world's time to sunrise"
    aliases: [ "dawn" ]

permissions:
  # Wildcard Permissions
  essentials.*:
    description: "Grants all permissions for the plugin"
    children:
      essentials.command.*: true
  essentials.command.*:
    description: "Grants all command-related permissions for the plugin"
    children:
      essentials.gamemode: true
      essentials.gamemode.other: true
      essentials.gamemode.all: true
      essentials.heal: true
      essentials.heal.other: true
      essentials.ping: true
      essentials.suicide: true
      essentials.time.quick.*: true
      essentials.whois: true
      essentials.whoami: true
  essentials.gamemode.*:
    description: "Grants all gamemode-related permissions for the plugin"
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
  essentials.gamemode.all:
    description: "Grants access to all gamemodes in /gamemode"
    children:
      essentials.gamemode.adventure: true
      essentials.gamemode.creative: true
      essentials.gamemode.survival: true
      essentials.gamemode.spectator: true
  essentials.time.quick.*:
    description: "Grants all quick time setting permissions"
    children:
      essentials.time.quick.day: true
      essentials.time.quick.midnight: true
      essentials.time.quick.night: true
      essentials.time.quick.noon: true
      essentials.time.quick.sunset: true
      essentials.time.quick.sunrise: true
  # New Command Permissions
  essentials.gamemode:
    description: "Allows you to alter your own gamemode"
  essentials.gamemode.others:
    description: "Allows you to alter another player's gamemode"
  essentials.gamemode.adventure:
    description: "Allows you to set your gamemode to Adventure"
  essentials.gamemode.creative:
    description: "Allows you to set your gamemode to Creative"
  essentials.gamemode.survival:
    description: "Allows you to set your gamemode to Survival"
  essentials.gamemode.spectator:
    description: "Allows you to set your gamemode to Spectator"
  essentials.heal:
    description: "Allows you to restore your own health"
  essentials.heal.others:
    description: "Allows you to restore another player's health"
  essentials.ping:
    description: "Allows you to view your ping to the server"
  essentials.suicide:
    description: "Allows you to forcibly end your player's life"
  essentials.time.quick.day:
    description: "Allows you to set the time to day"
  essentials.time.quick.midnight:
    description: "Allows you to set the time to midnight"
  essentials.time.quick.night:
    description: "Allows you to set the time to night"
  essentials.time.quick.noon:
    description: "Allows you to set the time to noon"
  essentials.time.quick.sunset:
    description: "Allows you to set the time to sunset"
  essentials.time.quick.sunrise:
    description: "Allows you to set the time to sunrise"
  essentials.whois:
    description: "Allows you view a player's /whois profile"
  essentials.whoami:
    description: "Allows you to view your own /whois profile"

  # Special Permissions
  essentials.gamemode.noalter:
    description: "Negates any alteration made to your gamemode by another player. Excluded from wildcard permissions"
    default: false
  essentials.disclosepermission:
    description: "Displays missing permission "
    default: op